name: "tests"
defaults:
  run:
    shell: bash
    working-directory: csd
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  pull_request:
    paths-ignore:
      - "**/README.md"
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: 'actions/checkout@v3'

    - uses: 'actions/setup-python@v4'
      with:
        python-version: ${{matrix.python-version}}
    
    - name: Setup black
      run: pip install black
      
    - name: Check style
      run: black --check .
    
    - name: install_requirements
      run: pip install -r requirements.txt
    
    - name: Run Tests
      env:
        PYTHONPATH: .
      run: pytest
